# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c744dfa2e8ff95303134e9472132ed672bdadecacf1bd91fcd085b39c22cd4d61941fc0dade180158ec4728920d7833afac03e1f514ee3b4be8d9d0112162c7e

test:
  secret_key_base: e8fea3dcc8f382a647d9a3453f4ad5f2af6ae5ed32a36f5d3be6ab0c22f0177bbf9121d91831e9713216eef0c140ea4b911f2c65b2dcb359e0e129eaa073dbf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
